
development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: naturegram-api_development
  pool:     5
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: naturegram-api_test
  pool:     5
  template: template0
